if(CPPI_ENABLE_COVERAGE)
  if(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang")
    add_compile_options(--coverage -O0 -g)
    add_link_options(--coverage)
    message(STATUS "cppi: coverage instrumentation enabled")
  else()
    message(WARNING "cppi: coverage is only supported with GCC or Clang")
  endif()
endif()
